trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Dmaven.test.failure.ignore=true'

steps:


    
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-e -X'
    goals: 'clean install'


- script: |
    # Start the browser driver in the background
    nohup xvfb-run -a --server-args="-screen 0 1920x1080x24" &
    # Run your Selenium tests using Maven
    mvn test
  displayName: 'Run Selenium Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/*.xml'
    failTaskOnFailedTests: true
